# Generated by Django 2.0.3 on 2019-05-18 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'cctm',
            },
        ),
        migrations.CreateModel(
            name='Challenges_Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('contest_name', models.CharField(max_length=50)),
                ('challenge_name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'challenges_leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Contest_Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
                ('contest_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contest_challenges',
            },
        ),
        migrations.CreateModel(
            name='Contest_Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('contest_name', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'contest_leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Create_Campus_Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=50)),
                ('contest_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_date', models.DateField()),
                ('end_time', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=5000)),
                ('prizes', models.CharField(max_length=5000)),
                ('rules', models.CharField(max_length=5000)),
                ('scoring', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'campus_contests',
            },
        ),
        migrations.CreateModel(
            name='Create_Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.Create_Challenge')),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
            options={
                'db_table': 'leaderboard',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('message', models.CharField(max_length=5000)),
                ('contest_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Online_Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=50)),
                ('contest_link', models.CharField(max_length=50)),
                ('contest_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_date', models.DateField()),
                ('end_time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'online_contests',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('contest_name', models.CharField(max_length=50)),
                ('contest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.Create_Campus_Contest')),
            ],
            options={
                'db_table': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_name', models.CharField(max_length=50)),
                ('contest_name', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
                ('time', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=7)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample', models.CharField(max_length=5)),
                ('score', models.DecimalField(decimal_places=0, max_digits=4)),
                ('challenge_name', models.CharField(max_length=50)),
                ('challenge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.Create_Challenge')),
            ],
            options={
                'db_table': 'testcases',
            },
        ),
        migrations.AddField(
            model_name='contest_challenges',
            name='challenge_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.Create_Challenge'),
        ),
        migrations.AddField(
            model_name='contest_challenges',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccms.Create_Campus_Contest'),
        ),
    ]
